### ISSUE TITLE
Breakout I2CDiscoverDevice ?

### ISSUE THREAD

**Issue by tablatronix** [bitbank2/BitBang_I2C#22]
have you considered abstracting I2CDiscoverDevice out to another library ? Just curious if there was something already doing this ID, afaik there is not...

**Comment by bitbank2** [comment]
I had originally written this function as a stand-alone Arduino sketch, but it seemed like something useful to include in BitBang_I2C since it doesn't take up that much space. The "friendly name" of each device must be supplied by your own code, but just having the constant IDs seemed like a useful thing to provide everyone. I created an example sketch with the friendly names and that seemed like a good compromise. You're welcome to use the code in another form if you prefer it that way.
